nginx:
  image: nginx:1.9.11
  expose:
    - "80"
  ports:
    - "80:80"
  volumes:
    - ./client/dist:/usr/share/nginx/html:ro
    - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  extra_hosts:
    - "localhost:192.168.99.1"

mongo:
  image: mongo:3.2
  command: mongod --storageEngine=wiredTiger
  ports:
    - "27017:27017"

