apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3.2
          command:
            - mongod
            - --storageEngine=wiredTiger
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo
