apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium
spec:
  replicas: 1
  selector:
    app: selenium
  template:
    metadata:
      name: selenium
      labels:
        app: selenium
    spec:
      volumes:
        - name: shm
          hostPath:
            path: /dev/shm
      containers:
        - name: selenium
          image: selenium/standalone-firefox-debug:2.52.0
          ports:
            - containerPort: 4444
            - containerPort: 5900
          imagePullPolicy: Always
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
---
apiVersion: v1
kind: Service
metadata:
  name: selenium
  labels:
    app: selenium
spec:
  ports:
    - name: client
      port: 4444
      targetPort: 4444
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
  selector:
    app: selenium
