apiVersion: v1
kind: ReplicationController
metadata:
  name: gocd-agent
  namespace: devops
spec:
  replicas: 1
  selector:
    app: gocd-agent
  template:
    metadata:
      name: gocd-agent
      labels:
        app: gocd-agent
    spec:
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker
        - name: pipelines
          hostPath:
            path: /home/core/pipelines
        - name: kubeconfig
          secret:
            secretName: kubeconfig.yml
        # CoreOS related dependencies
        - name: docker-dep
          hostPath:
            path: /usr/lib/libsystemd.so.0
        - name: libdevmapper
          hostPath:
            path: /usr/lib/libdevmapper.so.1.02
        - name: libgcrypt
          hostPath:
            path: /usr/lib/libgcrypt.so.20
      containers:
        - name: gocd-agent
          image: canthefason/gocd-agent:16.2.1
          env:
            - name: GO_SERVER
              value: gocd-server
          #livenessProbe:
            #httpGet:
              #path: /ping
              #port: 9000
            #initialDelaySeconds: 15
            #timeoutSeconds: 1
          ports:
            - containerPort: 8153
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2048Mi"
              cpu: "500m"
          #securityContext:
            #privileged: true
            #runAsUser: 0
          volumeMounts:
            - name: docker
              readOnly: true
              mountPath: /var/run/docker.sock
            - name: docker-bin
              readOnly: true
              mountPath: /bin/docker
            - name: pipelines
              mountPath: /var/lib/go-agent/pipelines
            - name: kubeconfig
              mountPath: /go/.kube/config
            - name: docker-dep
              readOnly: true
              mountPath: /usr/lib/libsystemd.so.0
            - name: libdevmapper
              readOnly: true
              mountPath: /usr/lib/libdevmapper.so.1.02
            - name: libgcrypt
              readOnly: true
              mountPath: /usr/lib/libgcrypt.so.20
